spring.application.name=modernbank-transfer

server.port = 8085
server.servlet.context-path = /modernbank/transfer

#postreSQL
spring.datasource.driverClassName= net.sf.log4jdbc.sql.jdbcapi.DriverSpy
spring.datasource.url= jdbc:log4jdbc:postgresql://${POSTGRES}/transfer
spring.datasource.username= postgres
spring.datasource.password= admin1234
spring.sql.init.encoding= UTF-8
spring.sql.init.schema-locations= classpath:sql/MODERNBANK_TRANSFER_DDL.sql
spring.sql.init.data-locations= classpath:sql/MODERNBANK_TRANSFER_DML.sql
spring.sql.init.mode= always

#mybatis
mybatis.type-aliases-package = com.modernbank.transfer.domain.entity
mybatis.mapper-locations = classpath:sql/*.xml
mybatis.configuration.map-underscore-to-camel-case = true

# Accont API URL
account.api.url = http://${ACCOUNT}/modernbank/account

# Customer API URL
customer.api.url = http://${CUSTOMER}/modernbank/customer

#kafka
kafka.bootstrapAddress=${KAFKA}
#CQRS
transfer.topic.name=transfer
updating.transfer.limit.topic.name=updating-transfer-limit
#Inter-bank transfer
b2b.transfer.topic.name=b2b-transfer
b2b.transfer.result.topic.name=b2b-transfer-result
spring.cloud.compatibility-verifier.enabled=false


#### environment ####
ACCOUNT=localhost:8081
B2BT=localhost:8082
CUSTOMER=localhost:8083
CQRS=localhost:8084
TRANSFER=localhost:8085
KAFKA=localhost:9092
POSTGRES=localhost:5432