spring.application.name = modernbank-b2bt
server.port = 8082
server.servlet.context-path = /modernbank

#Kafka
kafka.bootstrapAddress=${KAFKA}
b2b.transfer.topic.name=b2b-transfer
b2b.transfer.result.topic.name=b2b-transfer-result

#### environment ####
ACCOUNT=localhost:8081
B2BT=localhost:8082
CUSTOMER=localhost:8083
CQRS=localhost:8084
TRANSFER=localhost:8085
KAFKA=localhost:9092
POSTGRES=localhost:5432
