#### account application.properties
spring.application.name=modernbank-account

server.port = 8081
server.servlet.context-path = /modernbank/account

# postreSQL
spring.datasource.driverClassName = net.sf.log4jdbc.sql.jdbcapi.DriverSpy
spring.datasource.url = jdbc:log4jdbc:postgresql://${POSTGRES}/account
spring.datasource.username = postgres
spring.datasource.password = admin1234
spring.sql.init.encoding= UTF-8
spring.sql.init.schema-locations= classpath:sql/MODERNBANK_ACCOUNT_DDL.sql
spring.sql.init.data-locations= classpath:sql/MODERNBANK_ACCOUNT_DML.sql
spring.sql.init.mode= always

#mybatis
mybatis.type-aliases-package = com.modernbank.account.domain.entity
mybatis.mapper-locations = classpath:sql/*.xml
mybatis.configuration.map-underscore-to-camel-case = true

#API URL
account.api.url = http://${ACCOUNT}/modernbank/account
customer.api.url = http://${CUSTOMER}/modernbank/customer
cqrs.api.url = http://${ACCOUNT}/modernbank/account
transfer.api.url = http://${TRANSFER}/modernbank/transfer

kafka.bootstrapAddress=${KAFKA}
creating.account.topic.name=creating-account
updating.account.balance.topic.name=updating-account-balance
transaction.topic.name=transaction
spring.cloud.compatibility-verifier.enabled=false


#### environment ####
ACCOUNT=localhost:8081
B2BT=localhost:8082
CUSTOMER=localhost:8083
CQRS=localhost:8084
TRANSFER=localhost:8085
KAFKA=localhost:9092
POSTGRES=localhost:5432