spring.application.name=modernbank-customer

server.port = 8083
server.servlet.context-path = /modernbank/customer

#postreSQL
spring.datasource.driverClassName = net.sf.log4jdbc.sql.jdbcapi.DriverSpy
spring.datasource.url = jdbc:log4jdbc:postgresql://${POSTGRES}/customer
spring.datasource.username = postgres
spring.datasource.password = admin1234
spring.sql.init.encoding=UTF-8
spring.sql.init.mode= always
spring.sql.init.schema-locations= classpath:sql/MODERNBANK_CUSTOMER_DDL.sql
spring.sql.init.data-locations= classpath:sql/MODERNBANK_CUSTOMER_DML.sql

#mybatis
mybatis.type-aliases-package = com.modernbank.customer.domain.entity
mybatis.mapper-locations = classpath:sql/*.xml
mybatis.configuration.map-underscore-to-camel-case = true

# Accont API URL
account.api.url = http://${ACCOUNT}/modernbank/account
transfer.api.url = http://${TRANSFER}/modernbank/transfer

kafka.bootstrapAddress=${KAFKA}
creating.customer.topic.name=creating-customer
spring.cloud.compatibility-verifier.enabled=false

# application.properties (Spring Boot)
jwt.secret=67EL7cJ0U4OJ1wdqt+2w3Nqvy5HB9wwhx+DMsXMz9aY=


#### environment ####
ACCOUNT=localhost:8081
B2BT=localhost:8082
CUSTOMER=localhost:8083
CQRS=localhost:8084
TRANSFER=localhost:8085
KAFKA=localhost:9092
POSTGRES=localhost:5432